### PR TITLE
feat: Create base repository for coverage instrumenter

### PR DESCRIPTION
**Pull request by salet-gutierrez-jalafund**
#### Resolved task/US: ([CS-51 [SP-3] : Create base repository for Coverage Instrumenter](https://app.clickup.com/t/868avv54g))
* * * *

## What's in this pull request?

This is the initialization of the project with the necessary dependencies so that it can be evaluated, and the sonar for the workflow has been added.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This can be tested by running the following commands:
- To view dependencies:
```
./gredlew build
```
- To run the main class:
```
./gredlew bootRun
```
- To run tests:
```
./gredlew test
```

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by zrock-dev — APPROVED** [review]
LGTM

**Review by SebasthianSalpozz — CHANGES_REQUESTED** [review]
Good job, but the steps to run and test the project should be written in the readme file because not all people will see the Pr to know how to run the project

**Review by SebasthianSalpozz — CHANGES_REQUESTED** [review]
image


The Project doesnt build because  the main class name was not set I think

**Review by zamoranoalicia — APPROVED** [review]
LGTM

**Review by SebasthianSalpozz — COMMENTED** [review]
I think you lost the first comment that I give you

**Comment by zamoranoalicia** [comment]
I think we should go ahead with the code and later in the next commits we can add README with feedback from @SebasthianSalpozz

**Review by SebasthianSalpozz — APPROVED** [review]
Good job

**Pull request merged**
