### PR TITLE
Feat/cs 006/java agent setup

### PR DESCRIPTION
**Pull request by alex-paca-jalafund**
#### Resolved task/US: ([cs-006](https://app.clickup.com/t/868ata2yw))
* * * *

## What's in this pull request?
In this PR I uploaded the Agent and setup for generate the jar, also fixes that are needed to make it work correctly, in this PR can create the .jar config using "./gradlew shadowJar" 
Fixes:

- Path of Injecter Its using the path of the destiny directory, its setted by the momment has a static string
- CoverageCollector its now static this implementation its needed to be static because in the injecter its defining the CoverageCollector class and collect method has a static invokation

`mv.visitMethodInsn(
                INVOKESTATIC`
- updated tests
- Json nullPointerException problem

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

* [User Guide](https://universidadsalesian-my.sharepoint.com/:w:/g/personal/alex_paca_12432012_usalesiana_edu_bo/Eeq8Cxz0gENNsJjKl2QJ60oBUpFT7T_vOpNYoQo0aA7YQA?e=7nwpWm)

Using unitTesting and also with a end2end testing probing the usage of the jar in external projects to capture covered and not covered statements

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

## Notes How to use:

1. Run (./gradlew shadowJar)
expected:
Screenshot from 2024-11-28 19-18-42

2. Search the -all.jar in -> build/libs/ArgosInstrumentation-0.0.1-SNAPSHOT-all.jar
Screenshot from 2024-11-28 19-11-24

- - -
This change is [Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosInstrumentation/20)

### CODE REVIEW

**Review by zrock-dev — CHANGES_REQUESTED** [review]
Good job. I requested a bit of explanation about some stuff, but the overall implementation is ok.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-:-OCpIeNl8-p75r1RXhY6:b9hcn06)* status: all files reviewed, 3 unresolved discussions (waiting on @alex-paca-jalafund and @JosuePrado)

___
*[`src/main/java/edu/usb/argosinstrumentation/transformer/CoverageTransformer.java` line 18 at r1](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-OCpHTb03e0NRayGkSzW:-OCpHTb03e0NRayGkSzX:bvaxheu) ([raw file](https://github.com/softdevsix/argosinstrumentation/blob/0c768930ef6198309136ecd63e3ca73d8975ccc6/src/main/java/edu/usb/argosinstrumentation/transformer/CoverageTransformer.java#L18)):*
> ```Java
> public class CoverageTransformer implements ClassFileTransformer {
>     private final String projectName;
>     private CoverageCollector coverageCollector = new CoverageCollector();
> ```

Minor:

Could you please explain why `coverageCollect` has been moved to class field?
___
*[`src/test/java/edu/usb/argosinstrumentation/UtilsTest.java` line 0 at r1](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-OCpIMHECdyLOy-H6wE4:-OCpIMHECdyLOy-H6wE5:b-97i2yx) ([raw file](https://github.com/softdevsix/argosinstrumentation/blob/0c768930ef6198309136ecd63e3ca73d8975ccc6/src/test/java/edu/usb/argosinstrumentation/UtilsTest.java#L0)):*
Good job increasing the coverage.
___
*[`build.gradle.kts` line 100 at r1](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-OCpH03D2OlFIl5D5nyU:-OCpH03D2OlFIl5D5nyV:b-83mq3b) ([raw file](https://github.com/softdevsix/argosinstrumentation/blob/0c768930ef6198309136ecd63e3ca73d8975ccc6/build.gradle.kts#L100)):*
> ```Kotlin
>         attributes(
>             "Premain-Class" to "edu.usb.argosinstrumentation.agent.Agent", // Clase principal del agente
>             "Main-Class" to "edu.usb.argosinstrumentation.agent.Agent"    // Clase main para ejecución
> ```

Nit:

Spanglish



_Code quote:_
```Kotlin
            "Premain-Class" to "edu.usb.argosinstrumentation.agent.Agent", // Clase principal del agente
            "Main-Class" to "edu.usb.argosinstrumentation.agent.Agent"    // Clase main para ejecución
```

**Comment by alex-paca-jalafund** [comment]
> Good job. I requested a bit of explanation about some stuff, but the overall implementation is ok.
> 
> > Reviewed 10 of 10 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-:-OCpIeNl8-p75r1RXhY6:b9hcn06)_ status: all files reviewed, 3 unresolved discussions (waiting on @alex-paca-jalafund and @JosuePrado)
> 
> _[`src/main/java/edu/usb/argosinstrumentation/transformer/CoverageTransformer.java` line 18 at r1](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-OCpHTb03e0NRayGkSzW:-OCpHTb03e0NRayGkSzX:bvaxheu) ([raw file](https://github.com/softdevsix/argosinstrumentation/blob/0c768930ef6198309136ecd63e3ca73d8975ccc6/src/main/java/edu/usb/argosinstrumentation/transformer/CoverageTransformer.java#L18)):_
> 
> > ```java
> > public class CoverageTransformer implements ClassFileTransformer {
> >     private final String projectName;
> >     private CoverageCollector coverageCollector = new CoverageCollector();
> > ```
> 
> Minor:
> 
> Could you please explain why `coverageCollect` has been moved to class field?
> 
> _[`src/test/java/edu/usb/argosinstrumentation/UtilsTest.java` line 0 at r1](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-OCpIMHECdyLOy-H6wE4:-OCpIMHECdyLOy-H6wE5:b-97i2yx) ([raw file](https://github.com/softdevsix/argosinstrumentation/blob/0c768930ef6198309136ecd63e3ca73d8975ccc6/src/test/java/edu/usb/argosinstrumentation/UtilsTest.java#L0)):_ Good job increasing the coverage.
> 
> _[`build.gradle.kts` line 100 at r1](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-OCpH03D2OlFIl5D5nyU:-OCpH03D2OlFIl5D5nyV:b-83mq3b) ([raw file](https://github.com/softdevsix/argosinstrumentation/blob/0c768930ef6198309136ecd63e3ca73d8975ccc6/build.gradle.kts#L100)):_
> 
> > ```kotlin
> >         attributes(
> >             "Premain-Class" to "edu.usb.argosinstrumentation.agent.Agent", // Clase principal del agente
> >             "Main-Class" to "edu.usb.argosinstrumentation.agent.Agent"    // Clase main para ejecución
> > ```
> 
> Nit:
> 
> Spanglish
> 
> _Code quote:_
> 
> ```kotlin
>             "Premain-Class" to "edu.usb.argosinstrumentation.agent.Agent", // Clase principal del agente
>             "Main-Class" to "edu.usb.argosinstrumentation.agent.Agent"    // Clase main para ejecución
> ```

Yes, the explanation of why we are using directly the Collectorclass its because its the colllector who stores ProbeData, in the original implementation directly usages the Map<String, ClassData (finalInfo)> but in order to all the intrumentation works with the same finalInfo List we instance the collector and use his List of <String, ClassData>, because its also required for classes inside the Transform class in Transform Method its using the .put method, and also in the agent we are directly using the same List to the export of Json

**Review by zrock-dev — APPROVED** [review]
Alright. Good job.
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-:-OCpdqje4XhZotTv8Pv4:b-v9z34a)* status: all files reviewed, 3 unresolved discussions (waiting on @alex-paca-jalafund and @JosuePrado)

**Review by SebasthianSalpozz — APPROVED** [review]
Good job
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/softdevsix/argosinstrumentation/20#-:-OCph4vW5lKhjWFJ4Pbb:b1aypz3)* status: all files reviewed, 3 unresolved discussions (waiting on @alex-paca-jalafund, @JosuePrado, and @zrock-dev)

**Pull request merged**
